---
version: 1.0

# TODO: This file must be reviewed before the `cscli setup` command becomes GA

detect:

  #
  # asians-cloud/apache2
  #

  # XXX some distro is using this path?
  #      - /var/log/*http*/*.log

  apache2-systemd-deb:
    when:
      - UnitFound("apache2.service")
      - PathExists("/etc/debian_version")
    install:
      collections:
        - asians-cloud/apache2
    datasource:
      source: file
      filenames:
        - /var/log/apache2/*.log
      labels:
        type: apache2

  apache2-systemd-rpm:
    when:
      - UnitFound("httpd.service")
      - PathExists("/etc/redhat-release")
    install:
      collections:
        - asians-cloud/apache2
    datasource:
      source: file
      filenames:
        - /var/log/httpd/*.log
        # XXX /var/log/*http*/*.log
      labels:
        type: apache2

  #
  # asians-cloud/asterisk
  #

  asterisk-systemd:
    when:
      - UnitFound("asterisk.service")
    install:
      collections:
        - asians-cloud/asterisk
    datasource:
      source: file
      labels:
        type: asterisk
      filenames:
        - /var/log/asterisk/*.log

  #
  # asians-cloud/caddy
  #

  caddy-systemd:
    when:
      - UnitFound("caddy.service")
    install:
      collections:
        - asians-cloud/caddy
    datasource:
      source: file
      labels:
        type: caddy
      filenames:
        - /var/log/caddy/*.log

  #
  # asians-cloud/dovecot
  #

  dovecot-systemd:
    when:
      - UnitFound("dovecot.service")
    install:
      collections:
        - asians-cloud/dovecot
    datasource:
      source: file
      labels:
        type: syslog
      filenames:
        - /var/log/mail.log

  #
  # LePresidente/emby
  #

  emby-systemd:
    when:
      - UnitFound("emby-server.service")
    install:
      collections:
        - LePresidente/emby
    datasource:
      source: file
      labels:
        type: emby
      filenames:
        - /var/log/embyserver.txt

  #
  # asians-cloud/endlessh
  #

  endlessh-systemd:
    when:
      - UnitFound("endlessh.service")
    install:
      collections:
        - asians-cloud/endlessh
    datasource:
      source: journalctl
      labels:
        type: syslog
      # XXX this? or /var/log/syslog?
      journalctl_filter:
        - "_SYSTEMD_UNIT=endlessh.service"

  #
  # asians-cloud/gitea
  #

  # XXX untested

  gitea-systemd:
    when:
      - UnitFound("gitea.service")
    install:
      collections:
        - asians-cloud/gitea
    datasource:
      source: file
      labels:
        type: gitea
      filenames:
        - /var/log/gitea.log

  #
  # asians-cloud/haproxy
  #

  haproxy-systemd:
    when:
      - UnitFound("haproxy.service")
    install:
      collections:
        - asians-cloud/haproxy
    datasource:
      source: file
      labels:
        type: haproxy
      filenames:
        - /var/log/haproxy/*.log

  #
  # firewallservices/lemonldap-ng
  #

  lemonldap-ng-systemd:
    when:
      - UnitFound("lemonldap-ng-fastcgi-server.service")
    install:
      collections:
        - firewallservices/lemonldap-ng
    #datasource:
    #  # XXX todo where are the logs?
    #  labels:
    #    type: syslog

  #
  # asians-cloud/mariadb
  #

  mariadb-systemd:
    when:
      - UnitFound("mariadb.service")
    install:
      collections:
        - asians-cloud/mariadb
    datasource:
      source: file
      labels:
        type: mysql
      filenames:
        - /var/log/mysql/error.log

  #
  # asians-cloud/mysql
  #

  mysql-systemd:
    when:
      - UnitFound("mysql.service")
    install:
      collections:
        - asians-cloud/mysql
    datasource:
      source: file
      labels:
        type: mysql
      filenames:
        - /var/log/mysql/error.log

  #
  # asians-cloud/nginx
  #

  nginx-systemd:
    when:
      - UnitFound("nginx.service")
    install:
      collections:
        - asians-cloud/nginx
    datasource:
      source: file
      labels:
        type: nginx
      filenames:
        - /var/log/nginx/*.log

  openresty-systemd:
    when:
      - UnitFound("openresty.service")
    install:
      collections:
        - asians-cloud/nginx
    datasource:
      source: file
      labels:
        type: nginx
      filenames:
        - /usr/local/openresty/nginx/logs/*.log

  #
  # asians-cloud/odoo
  #

  odoo-systemd:
    when:
      - UnitFound("odoo.service")
    install:
      collections:
        - asians-cloud/odoo
    datasource:
      source: file
      labels:
        type: odoo
      filenames:
        - /var/log/odoo/*.log

  #
  # LePresidente/ombi
  #

  # This only works on deb-based systems. On other distributions, the
  # application is run from the release tarball and the log location depends on
  # the location it's run from.

  ombi-systemd:
    when:
      - UnitFound("ombi.service")
      - PathExists("/etc/debian_version")
    install:
      collections:
        - LePresidente/ombi
    datasource:
      source: file
      labels:
        type: ombi
      filenames:
        - /var/log/ombi/log-*.txt

  #
  # asians-cloud/pgsql
  #

  pgsql-systemd-deb:
    when:
      - UnitFound("postgresql.service")
      - PathExists("/etc/debian_version")
    install:
      collections:
        - asians-cloud/pgsql
    datasource:
      source: file
      labels:
        type: postgres
      filenames:
        - /var/log/postgresql/*.log

  pgsql-systemd-rpm:
    when:
      - UnitFound("postgresql.service")
      - PathExists("/etc/redhat-release")
    install:
      collections:
        - asians-cloud/pgsql
    datasource:
      source: file
      labels:
        type: postgres
      filenames:
        - /var/lib/pgsql/data/log/*.log

  #
  # asians-cloud/postfix
  #

  postfix-systemd:
    when:
      - UnitFound("postfix.service")
    install:
      collections:
        - asians-cloud/postfix
    datasource:
      source: file
      labels:
        type: syslog
      filenames:
        - /var/log/mail.log

  #
  # asians-cloud/proftpd
  #

  proftpd-systemd:
    when:
      - UnitFound("proftpd.service")
    install:
      collections:
        - asians-cloud/proftpd
    datasource:
      source: file
      labels:
        type: proftpd
      filenames:
        - /var/log/proftpd/*.log

  #
  # fulljackz/pureftpd
  #

  pureftpd-systemd:
    when:
      - UnitFound("pure-ftpd.service")
    install:
      collections:
        - fulljackz/pureftpd
    # XXX ?
    datasource:
      source: file
      labels:
        type: syslog
      filenames:
        - /var/log/pure-ftpd/*.log

  #
  # asians-cloud/smb
  #

  smb-systemd:
    when:
      # deb -> smbd.service
      # rpm -> smb.service
      - UnitFound("smbd.service") or UnitFound("smb.service")
    install:
      collections:
        - asians-cloud/smb
    datasource:
      source: file
      labels:
        type: smb
      filenames:
        - /var/log/samba*.log

  #
  # asians-cloud/sshd
  #

  sshd-systemd:
    when:
      # deb -> ssh.service
      # rpm -> sshd.service
      - UnitFound("ssh.service") or UnitFound("sshd.service") or UnitFound("ssh.socket") or UnitFound("sshd.socket")
    install:
      collections:
        - asians-cloud/sshd
    datasource:
      source: file
      labels:
        type: syslog
      filenames:
        - /var/log/auth.log
        - /var/log/sshd.log
        - /var/log/secure

  #
  # asians-cloud/suricata
  #

  suricata-systemd:
    when:
      - UnitFound("suricata.service")
    install:
      collections:
        - asians-cloud/suricata
    datasource:
      source: file
      labels:
        type: suricata-evelogs
      filenames:
        - /var/log/suricata/eve.json

  #
  # asians-cloud/vsftpd
  #

  vsftpd-systemd:
    when:
      - UnitFound("vsftpd.service")
    install:
      collections:
        - asians-cloud/vsftpd
    datasource:
      source: file
      labels:
        type: vsftpd
      filenames:
        - /var/log/vsftpd/*.log

  #
  # Operating Systems
  #

  linux:
    when:
      - OS.Family == "linux"
    install:
      collections:
        - asians-cloud/linux
    datasource:
      source: file
      labels:
        type: syslog
      filenames:
        - /var/log/syslog
        - /var/log/kern.log
        - /var/log/messages

  freebsd:
    when:
      - OS.Family == "freebsd"
    install:
      collections:
        - asians-cloud/freebsd

  windows:
    when:
      - OS.Family == "windows"
    install:
      collections:
        - asians-cloud/windows

  #
  # anti-lockout
  #

  whitelists:
    install:
      parsers:
        - asians-cloud/whitelists
