# .github/workflows/build-docker-image.yml
name: build

on:
  release:
    types:
      - prereleased

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.20.1"]

    name: Build and upload binary package
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: "Set up Go ${{ matrix.go-version }}"
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build the binaries
        run: make release

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: crowdsec-release.tgz application/x-gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
